/**
* File generated by ENIGMA © 2016 Steven Jackson
*
*/
module.exports = function (service) {
  // var server = service.using('server');      // USE THIS IF YOU NEED TO EXPOSE THE EXPRESS SERVER OBJECT
  // var app = service.using('app');            // USE THIS IF YOU NEED TO EXPOSE THE EXPRESS APP OBJECT
  
  /**
  * EXAMPLE
  *
  */
  // server.endpoint('get', '/[service name]', function (req, res) {
	// 	var jsonData = { message: 'Service [service name] is running' };
  //  res.render('index', { jsonData: jsonData });
  // });
};
